### ISSUE TITLE
Deposit should accept basic metadata

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/repository-api#29]
- [x] admin policy
- [x] collection
- [x] catkey
- [x] source ID

**Comment by mjgiarlo** [comment]
@jcoyne For now, should this codebase accept all three of these parameters without answering the question of which APO should be used (since we were planning to handle that upstream in https://github.com/sul-dlss/google-books/issues/1)? I didn't think we were trying to answer that question in the repository-api work.
